[project]
name = "tableauknockoff"
version = "0.1.0"
description = "A FastAPI application"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.109.0",
    "fastui>=0.9.0",
    "langchain-groq>=1.1.2",
    "langgraph>=1.1.6",
    "plotly>=6.7.0",
    "psycopg2-binary>=2.9.11",
    "sqlalchemy>=2.0.49",
    "uvicorn[standard]>=0.27.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "httpx>=0.26.0",
    "black>=26.3.1",
]
