"""
The module to allow LLM interaction with the agent.
"""

from typing import Annotated
from langchain_core.prompts import PromptTemplate
from langchain_groq import ChatGroq
from typing_extensions import Doc
from .schemas import SQLBlueprint, TableSchema

MODEL_ID = "openai/gpt-oss-120b"


PLANNER_PROMPT = PromptTemplate(
    template="""You are a strict BI query planner that converts natural language into a structured SQL query plan.

Database schema:
{db_schema}

User question:
{user_question}

Rules:
- Use ONLY tables and columns present in the schema
- NEVER hallucinate columns or tables
- Always include at least ONE metric
- Metrics MUST use aggregation: sum, avg, count, min, max, count_distinct
- Only numeric columns should be used for aggregations (except count)
- Grouping columns MUST exist in the table
- Filters must match column types logically
- Use LIKE only for text columns
- Use IN only with a list of values
- Prefer simple queries over complex ones
- If the query is ambiguous, choose the most reasonable interpretation
- Choose the most relevant table based on the question
- Prefer tables that contain both grouping columns and metric columns
- ORDER BY can use either a column name or a metric alias

Output requirements:
- Return ONLY valid JSON
- Do NOT include explanations, comments, or markdown


Return JSON following this structure:
{
  "table": "string",
  "metrics": [{"column": "string", "aggregation": "sum|avg|count|min|max|count_distinct", "alias": "string"}],
  "group_by": ["string"],
  "filters": [{"column": "string", "operator": "=|!=|>|<|>=|<=|LIKE|IN", "value": "string|number|list"}],
  "order_by": [{"column": "string", "sort_type": "asc|desc"}],
  "limit": 100
}
""",
    input_variables=["db_schema", "user_question"],
)

PLANNER_RETRY_PROMPT = PromptTemplate(
    template="""You are a strict BI query planner fixing an invalid SQL query plan.

Database schema:
{db_schema}

User question:
{user_question}

Previous SQL blueprint:
{previous_blueprint}

Error:
{error}

Your task:
Fix the SQL blueprint so that it is valid and executable.

Rules:
- Use ONLY tables and columns present in the schema
- NEVER hallucinate columns or tables
- Always include at least ONE metric
- Metrics MUST use aggregation: sum, avg, count, min, max, count_distinct
- Only numeric columns should be used for aggregations (except count)
- Grouping columns MUST exist in the table
- Fix invalid columns, operators, or structure based on the error
- If a column does not exist, replace it with the closest valid column
- Ensure filters and operators are valid
- Ensure ORDER BY columns exist (or match metric aliases)
- Choose the most relevant table based on the question
- Prefer tables that contain both grouping columns and metric columns
- ORDER BY can use either a column name or a metric alias

Output requirements:
- Return ONLY valid JSON
- Do NOT include explanations, comments, or markdown

Return JSON following this structure:
{
  "table": "string",
  "metrics": [{"column": "string", "aggregation": "sum|avg|count|min|max|count_distinct", "alias": "string"}],
  "group_by": ["string"],
  "filters": [{"column": "string", "operator": "=|!=|>|<|>=|<=|LIKE|IN", "value": "string|number|list"}],
  "order_by": [{"column": "string", "sort_type": "asc|desc"}],
  "limit": 100
}
""",
    input_variables=["db_schema", "user_question", "previous_blueprint", "error"],
)


class LLMPlanner:
    """The LLM planner to generate SQL blueprint from the question and database schema."""

    def __init__(self):
        llm: ChatGroq = ChatGroq(model=MODEL_ID, temperature=0, max_retries=2)
        self.llm = llm.with_structured_output(  # pyright: ignore[reportUnknownMemberType, reportUnannotatedClassAttribute]  # pyright: ignore[reportUnknownMemberType]
            SQLBlueprint
        )

    def __call__(
        self,
        question: Annotated[str, Doc("The natural language question from the user.")],
        db_schema: Annotated[list[TableSchema], Doc("The database schema.")],
        retry: Annotated[
            bool, Doc("Whether if this is a retry attempt or an initial attempt.")
        ] = False,
        previous_blueprint: Annotated[
            SQLBlueprint | None,
            Doc("The previous SQL blueprint generated by the AI, if existing."),
        ] = None,
        error_message: Annotated[
            str | None,
            Doc("The error message from the previous execution attempt, if existing."),
        ] = None,
    ) -> SQLBlueprint:
        """Generate SQL blueprint from the question and database schema."""
        if retry and previous_blueprint:
            return (  # pyright: ignore[reportReturnType, reportUnknownVariableType, reportUnknownMemberType]
                PLANNER_RETRY_PROMPT
                | self.llm  # pyright: ignore[reportUnknownMemberType]
            ).invoke(
                {
                    "db_schema": self.format_schema(db_schema),
                    "user_question": question,
                    "previous_blueprint": previous_blueprint.model_dump_json(),
                    "error": error_message,
                }
            )
        return (  # pyright: ignore[reportReturnType, reportUnknownMemberType, reportUnknownVariableType]
            PLANNER_PROMPT | self.llm  # pyright: ignore[reportUnknownMemberType]
        ).invoke(
            {
                "db_schema": self.format_schema(db_schema),
                "user_question": question,
            }
        )

    @staticmethod
    def format_schema(
        schema: Annotated[
            list[TableSchema], Doc("The list of database tables' schema.")
        ],
    ) -> str:
        """
        Convert structured TableSchema list into an LLM-friendly schema string.
        """

        lines: list[str] = []

        for table in schema:
            col_lines: list[str] = []

            type_map = {c["name"]: c["type"] for c in table.column_types}

            for col in table.columns:
                col_type = type_map.get(col)
                if col_type is None:
                    raise ValueError(f"Missing column type for column: {col}")

                role = "dimension"

                if col_type == "numeric":
                    role = "metric"
                elif col_type == "time":
                    role = "time"

                col_lines.append(f"{col} ({col_type}, {role})")

            line = f"{table.name}: [{', '.join(col_lines)}]"

            if table.primary_keys:
                line += f" | PK: ({', '.join(table.primary_keys)})"

            if table.foreign_keys:
                fk_str = ", ".join(
                    f"{fk['column']} -> {fk['references']}" for fk in table.foreign_keys
                )
                line += f" | FK: ({fk_str})"

            lines.append(line)

        return "\n".join(lines)
