"""
The module to allow LLM interaction with the agent.
"""

import os
from pathlib import Path
from typing import Annotated, Any, cast

from dotenv import load_dotenv
from langchain_core.runnables import RunnableSerializable
from langchain_groq import ChatGroq
from typing_extensions import Doc

from agent.prompts import PLANNER_PROMPT, PLANNER_RETRY_PROMPT, VALIDATOR_PROMPT
from agent.schemas import SQLBlueprint, TableSchema, ValidationResult

if not (path := Path(".env").resolve()).exists():
    raise FileNotFoundError(f"Missing .env file at path: {path}")

_ = load_dotenv(path)

MODEL_ID = "openai/gpt-oss-120b"


class BaseLLM:
    """Base LLM class to be inherited by specific LLM implementations."""

    def __init__(
        self,
        api_key: Annotated[
            str | None, Doc(f"The API key for accessing Groq API.")
        ] = None,
    ):
        resolved_api_key: str | None = api_key if api_key else os.getenv("GROQ_API_KEY")
        self.llm: ChatGroq = ChatGroq(
            model=MODEL_ID,
            api_key=resolved_api_key,  # pyright: ignore[reportArgumentType]
            temperature=0.0,
            max_retries=2,
            model_kwargs={"response_format": {"type": "json_object"}},
        )

    @staticmethod
    def format_schema(
        schema: Annotated[
            list[TableSchema], Doc("The list of database tables' schema.")
        ],
    ) -> str:
        """
        Convert structured TableSchema list into an LLM-friendly schema string.
        """

        lines: list[str] = []

        for table in schema:
            col_lines: list[str] = []

            type_map = {c["name"]: c["type"] for c in table.column_types}

            for col in table.columns:
                col_type = type_map.get(col)
                if col_type is None:
                    raise ValueError(f"Missing column type for column: {col}")

                role = "dimension"

                if col_type == "numeric":
                    role = "metric"
                elif col_type == "time":
                    role = "time"

                col_lines.append(f"{col} ({col_type}, {role})")

            line = f"{table.name}: [{', '.join(col_lines)}]"

            if table.primary_keys:
                line += f" | PK: ({', '.join(table.primary_keys)})"

            if table.foreign_keys:
                fk_str = ", ".join(
                    f"{fk['column']} -> {fk['references']}" for fk in table.foreign_keys
                )
                line += f" | FK: ({fk_str})"

            lines.append(line)

        return "\n".join(lines)


class LLMPlanner(BaseLLM):
    """The LLM planner to generate SQL blueprint from the question and database schema."""

    planner_chain: RunnableSerializable[
        dict[str, Any], SQLBlueprint  # pyright: ignore[reportExplicitAny]
    ]
    retry_planner_chain: RunnableSerializable[
        dict[str, Any], SQLBlueprint  # pyright: ignore[reportExplicitAny]
    ]

    def __init__(
        self,
        api_key: Annotated[
            str | None, Doc(f"The API key for accessing Groq API.")
        ] = None,
    ):
        super().__init__(api_key=api_key)
        structured_llm = cast(
            RunnableSerializable[
                Any, SQLBlueprint  # pyright: ignore[reportExplicitAny]
            ],
            self.llm.with_structured_output(  # pyright: ignore[reportUnknownMemberType]
                SQLBlueprint, method="json_mode"
            ),
        )

        self.planner_chain = PLANNER_PROMPT | structured_llm
        self.retry_planner_chain = PLANNER_RETRY_PROMPT | structured_llm

    def __call__(
        self,
        question: Annotated[str, Doc("The natural language question from the user.")],
        db_schema: Annotated[list[TableSchema], Doc("The database schema.")],
        retry: Annotated[
            bool, Doc("Whether if this is a retry attempt or an initial attempt.")
        ] = False,
        previous_blueprint: Annotated[
            SQLBlueprint | None,
            Doc("The previous SQL blueprint generated by the AI, if existing."),
        ] = None,
        error_message: Annotated[
            str | None,
            Doc("The error message from the previous execution attempt, if existing."),
        ] = None,
    ) -> SQLBlueprint:
        """Generate SQL blueprint from the question and database schema."""
        if retry and previous_blueprint:
            return self.retry_planner_chain.invoke(
                input={
                    "db_schema": self.format_schema(db_schema),
                    "user_question": question,
                    "previous_blueprint": previous_blueprint.model_dump_json(),
                    "error": error_message,
                }
            )
        return self.planner_chain.invoke(
            input={
                "db_schema": self.format_schema(db_schema),
                "user_question": question,
            }
        )


class LLMValidator(BaseLLM):
    """The LLM validator to validate the generated SQL query against the question and database schema."""

    llm_chain: RunnableSerializable[
        dict[str, Any], ValidationResult  # pyright: ignore[reportExplicitAny]
    ]

    def __init__(
        self,
        api_key: Annotated[
            str | None, Doc(f"The API key for accessing Groq API.")
        ] = None,
    ):
        super().__init__(api_key=api_key)
        structured_llm = cast(
            RunnableSerializable[
                Any, ValidationResult  # pyright: ignore[reportExplicitAny]
            ],
            self.llm.with_structured_output(  # pyright: ignore[reportUnknownMemberType]
                ValidationResult, method="json_mode"
            ),
        )
        self.llm_chain = VALIDATOR_PROMPT | structured_llm

    def __call__(
        self,
        question: Annotated[str, Doc("The natural language question from the user.")],
        sql_dialect: Annotated[
            str,
            Doc("The SQL dialect to be used for query generation."),
        ],
        sql_query: Annotated[str, Doc("The compiled SQL query to be validated.")],
    ) -> ValidationResult:
        """Validate generated SQL query against the question and database schema."""
        return self.llm_chain.invoke(
            input={
                "question": question,
                "sql_dialect": sql_dialect,
                "sql_query": sql_query,
            }
        )
