"""The state used for LangGraph agent."""

from typing import Any, Literal
from pydantic import BaseModel, Field


class Filter(BaseModel):
    column: str = Field(description="The name of the database column to filter on.")
    operator: Literal[">=", "<=", ">", "<", "==", "!=", "like", "in"] = Field(
        description="The logical operator to apply to the column and value."
    )
    value: Any = Field(  # pyright: ignore[reportAny, reportExplicitAny]
        description="The value to compare the column against. Use a list for the 'in' operator."
    )


class Metric(BaseModel):
    column: str = Field(
        description="The numeric column name to perform a calculation on."
    )
    aggregation: Literal["sum", "avg", "count", "min", "max", "count_distinct"] = Field(
        description="The mathematical function to apply to the metric column."
    )


class OrderBy(BaseModel):
    column: str = Field(
        description="The column name used to sort the final result set."
    )
    sort_type: Literal["asc", "desc"] = Field(
        description="The sort order: ascending (asc) or descending (desc)."
    )


class SQLBlueprint(BaseModel):
    table: str = Field(description="The name of the database table to query.")
    metrics: list[Metric] = Field(
        default_factory=list,
        description="A list of quantitative calculations to perform.",
    )
    hue_cols: list[str] = Field(
        default_factory=list,
        description="A list of categorical columns to group the data by.",
    )
    filters: list[Filter] = Field(
        default_factory=list,
        description="The set of criteria used to restrict which rows are retrieved.",
    )
    order_by: list[OrderBy] = Field(
        default_factory=list,
        description="Instructions for sorting the resulting data rows.",
    )
    limit: int = Field(
        default=100,
        description="The maximum number of rows to return from the database.",
    )


class ChartConfig(BaseModel):
    chart_type: Literal["bar", "line", "scatter", "pie", "area"] = Field(
        description="The type of chart to plot."
    )
    x: str = Field(description="The column name to be plotted on the X-axis.")
    y: str = Field(description="The column name to be plotted on the Y-axis.")
    hue: str | None = Field(
        default=None,
        description="An optional column name to use for color encoding (e.g., for grouping).",
    )


class GraphState(BaseModel):
    question: str = Field(
        description="The original natural language question asked by the user."
    )
    db_schema: dict[str, Any] = Field(  # pyright: ignore[reportExplicitAny]
        default_factory=dict,
        description="Database schema, describing the database tables, columns, and data types.",
    )
    sql_blueprint: SQLBlueprint | None = Field(
        default=None,
        description="The structured plan generated by the AI to answer the question.",
    )
    sql: str | None = Field(
        default=None,
        description="The compiled SQLAlchemy or raw SQL string for debugging and execution.",
    )
    preview: list[dict[str, Any]] | None = Field(  # pyright: ignore[reportExplicitAny]
        default=None,
        description="The preview of the SQL query results (limited rows to maximum 10).",
    )
    chart_config: ChartConfig | None = Field(
        default=None,
        description="Configuration for how to visualize the resulting data.",
    )
    error: str | None = Field(
        default=None,
        description="A detailed error message if any step in the graph fails.",
    )
