"""The state used for LangGraph agent and database schematics."""

from typing import Any, Literal
from pydantic import BaseModel, Field, model_validator


class TableSchema(BaseModel):
    """Represents the schema of a database table."""

    name: str = Field(description="The name of the database table.")
    columns: list[str] = Field(
        description="The list of column names in the database table.",
    )
    column_types: list[dict[str, str]] = Field(
        description="The list of column names along with their data types in the database table.",
    )
    primary_keys: list[str] = Field(
        default_factory=list,
        description="The list of column names that are primary keys in the database table.",
    )
    foreign_keys: list[dict[str, str]] = Field(
        default_factory=list,
        description=(
            "The list of foreign key relationships in the database table. Each relationship is represented as a dictionary with 'column' and 'references' keys."
        ),
    )


class ColumnRef(BaseModel):
    """Mapping of column name with its table."""

    table: str = Field(description="Name of the database table.")
    column: str = Field(description="Column belonging to database table.")


class Filter(BaseModel):
    """Represents a filter condition to be applied to a column in a SQL query."""

    column: ColumnRef = Field(
        description="The column (with table reference) to filter on."
    )
    operator: Literal["=", "!=", ">", "<", ">=", "<=", "LIKE", "IN"] = Field(
        description="The logical operator to apply to the column and value."
    )
    value: str | int | float | list[str | int | float] = Field(
        description="The value to compare the column against. Use a list for the 'in' operator."
    )

    @model_validator(mode="after")
    def validate_value_for_in(self):
        if self.operator == "IN" and not isinstance(self.value, list):
            raise ValueError("IN operator requires list value")
        return self


class Metric(BaseModel):
    """Represents a mathematical aggregation to be performed on a column in a SQL query."""

    column: ColumnRef = Field(
        description="The column (with table reference) to perform a calculation on."
    )
    aggregation: Literal["sum", "avg", "count", "min", "max", "count_distinct"] = Field(
        description="The aggregation to apply to the metric column."
    )
    alias: str | None = Field(
        default=None,
        description="An optional alias for the resulting metric column in the output.",
    )


class OrderBy(BaseModel):
    """Represents a sorting technique to be applied to a column in a SQL query result."""

    col: ColumnRef | str = Field(
        description="The column (with table reference) OR metric alias used to sort the final result set."
    )
    sort_type: Literal["asc", "desc"] = Field(
        description="The sort order: ascending (asc) or descending (desc)."
    )


class SQLBlueprint(BaseModel):
    """Represents the structured plan for generating a SQL query."""

    columns: list[ColumnRef] = Field(
        description="List of column selections where each item maps a table name to a column name."
    )
    group_by: list[ColumnRef] = Field(
        default_factory=list,
        description="A list of categorical columns to group the data by.",
    )
    metrics: list[Metric] = Field(
        default_factory=list,
        description="A list of quantitative calculations to perform.",
    )
    filters: list[Filter] = Field(
        default_factory=list,
        description="The set of criteria used to restrict which rows are retrieved.",
    )
    order_by: list[OrderBy] = Field(
        default_factory=list,
        description="Instructions for sorting the resulting data rows.",
    )
    limit: int = Field(
        default=100,
        description="The maximum number of rows to return from the database.",
    )


class ChartConfig(BaseModel):
    """Represents the configuration for visualizing the SQL query results."""

    chart_type: Literal["bar", "line", "scatter", "pie", "area"] = Field(
        description="The type of chart to plot."
    )
    x: str = Field(description="The column name to be plotted on the X-axis.")
    y: str = Field(description="The column name to be plotted on the Y-axis.")
    hue: str | None = Field(
        default=None,
        description="An optional column name to use for color encoding (e.g., for grouping).",
    )


class GraphState(BaseModel):
    """Represents the state used within the LangGraph agent."""

    question: str = Field(
        description="The original natural language question asked by the user."
    )
    db_schema: list[TableSchema] = Field(
        default_factory=list,
        description="Database schema, describing the database tables, columns, and data types.",
    )
    sql_blueprint: SQLBlueprint | None = Field(
        default=None,
        description="The structured plan generated by the AI to answer the question.",
    )
    sql: str | None = Field(
        default=None,
        description="The compiled SQLAlchemy or raw SQL string for debugging and execution.",
    )
    preview: list[dict[str, Any]] | None = Field(  # pyright: ignore[reportExplicitAny]
        default=None,
        description="The preview of the SQL query results (limited rows to maximum 10).",
    )
    chart_config: ChartConfig | None = Field(
        default=None,
        description="Configuration for how to visualize the resulting data.",
    )
    error: str | None = Field(
        default=None,
        description="A detailed error message if any step in the graph fails.",
    )
