"""The state used for LangGraph agent."""

from typing import Any, Literal
from pydantic.fields import Field
from pydantic.functional_validators import model_validator
from pydantic.main import BaseModel

from database.schemas import SQLBlueprint, TableSchema


class ValidationResult(BaseModel):
    """Represents the result of validating a generated SQL query."""

    is_valid: bool = Field(description="Indicates whether the SQL query is valid.")
    confidence_score: float = Field(
        description="A calibrated confidence score between 0.0 and 1.0 representing how likely the SQL correctly answers the question.",
        ge=0.0,
        le=1.0,
    )
    error_message: str | None = Field(
        default=None,
        description="Detailed error message if the SQL query is invalid.",
    )

    @model_validator(mode="after")
    def validate_error_message(self):
        if not self.is_valid and not self.error_message:
            raise ValueError("Error message required when SQL is invalid")
        return self


class ChartConfig(BaseModel):
    """Configuration for generating interactive Plotly HTML charts."""

    chart_type: Literal["bar", "line", "scatter", "pie", "area"] = Field(
        description="The type of chart that best visualizes the data trend or comparison."
    )

    x: str = Field(
        description="The column for the independent variable. For Cartesian charts (bar, line, etc.), this is the X-axis (e.g., 'date' or 'category'). For Pie charts, this is the 'label' or 'name' column."
    )

    y: str = Field(
        description="The column for the dependent variable. For Cartesian charts, this is the Y-axis (must be numeric). For Pie charts, this is the 'value' or 'slice size' column (must be numeric)."
    )

    color: str | None = Field(
        default=None,
        description="The column used to group data into different colors/series (e.g., 'region' or 'status'). Leave null if there is only one series.",
    )

    title: str = Field(
        description="A concise, descriptive title for the chart that explains the relationship being visualized (e.g., 'Monthly Revenue by Region')."
    )

    @model_validator(mode="after")
    def validate_dimensions(self):
        if not self.x or not self.y:
            raise ValueError(
                f"{self.chart_type} requires both 'x' and 'y' column assignments."
            )
        return self


class GraphState(BaseModel):
    """Represents the state used within the LangGraph agent."""

    question: str = Field(
        description="The original natural language question asked by the user."
    )
    sql_blueprint: SQLBlueprint | None = Field(
        default=None,
        description="The structured plan generated by the AI to answer the question.",
    )
    sql: str | None = Field(
        default=None,
        description="The compiled SQLAlchemy query for debugging and execution.",
    )
    preview: list[dict[str, Any]] = Field(  # pyright: ignore[reportExplicitAny]
        default_factory=list,
        description="The preview of the SQL query results (limited rows to maximum 10).",
    )
    db_schema: list[TableSchema] = Field(
        default_factory=list,
        description="The database schema information used for SQL generation and validation.",
    )
    chart_config: ChartConfig | None = Field(
        default=None,
        description="Configuration for how to visualize the resulting data.",
    )
    error: str | None = Field(
        default=None,
        description="A detailed error message if any step in the graph fails.",
    )

    retry_count: int = Field(
        default=0,
        description="The amount of times the agent retries planning SQL query.",
    )


class AgentInput(BaseModel):
    """Input question for the agent."""

    question: str


class AgentOutput(BaseModel):
    success: bool = Field(
        description="Whether the agent successfully produced a valid result."
    )
    sql: str | None = Field(
        default=None,
        description="The compiled SQLAlchemy or raw SQL string for debugging and execution.",
    )
    chart_config: ChartConfig | None = Field(
        default=None,
        description="Configuration for how to visualize the resulting data.",
    )
    error: str | None = Field(
        default=None,
        description="A detailed error message if any step in the graph fails.",
    )

    @model_validator(mode="after")
    def validate_success(self):
        match (self.success, bool(self.error)):
            case (True, True):
                raise ValueError("Error message must be null when success is True")

            case (False, False):
                raise ValueError("Error message required when success is False")

            case (True, False) if not all([self.sql, self.chart_config]):
                raise ValueError(
                    "SQL and chart_config must be provided when success is True"
                )

            case _:
                return self
